FIND_PATH(MySQL_INCLUDE_DIR mysql.h /usr/include/mysql/ /usr/local/include/mysql/)

FIND_LIBRARY(MySQL_LIBRARY mysqlclient /usr/lib /usr/local/lib)

IF (MySQL_INCLUDE_DIR AND MySQL_LIBRARY)
  SET(MySQL_FOUND TRUE)
ENDIF(MySQL_INCLUDE_DIR AND MySQL_LIBRARY)


IF(MySQL_FOUND)
  IF(NOT MySQL_FIND_QUIETLY)
    MESSAGE(STATUS "Found MySQL: ${MySQL_LIBRARY}")
  ENDIF(NOT MySQL_FIND_QUIETLY)
ELSE(MySQL_FOUND)
  IF(MySQL_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find MySQL.")
  ENDIF(MySQL_FIND_REQUIRED)
ENDIF(MySQL_FOUND)

